# Generated by Django 5.2 on 2026-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='extraction_time_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datafile',
            name='file_size_bytes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datafile',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='SUCCESS', max_length=20),
        ),
    ]
