# Generated by Django 5.0.3 on 2026-04-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('db_type', models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('MONGO', 'MongoDB'), ('CLICKHOUSE', 'ClickHouse')], max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('database_name', models.CharField(max_length=255)),
            ],
        ),
    ]
